version: '3.8'

services:
  postgres-07:
    image: postgres:14
    container_name: rag-postgres-07
    environment:
      POSTGRES_USER: raguser
      POSTGRES_PASSWORD: ragpassword
      POSTGRES_DB: ragdb
    volumes:
      - postgres_data-07:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U raguser -d ragdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  qdrant-07:
    image: qdrant/qdrant:latest
    container_name: rag-qdrant-07
    volumes:
      - qdrant_data-07:/qdrant/storage
    ports:
      - "6333:6333"
      - "6334:6334"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend-07:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: rag-backend-07
    volumes:
      - ./data-07:/app/data
    ports:
      - "8000:8000"
    environment:
      - HUGGING_FACE_HUB_TOKEN=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
      - DATABASE_URL=postgresql://raguser:ragpassword@postgres:5432/ragdb
      - QDRANT_URL=http://qdrant:6333
      - JWT_SECRET=${JWT_SECRET:-supersecretkey}
    depends_on:
      - postgres-07
      - qdrant-07
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  frontend-07:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: rag-frontend-07
    ports:
      - "3000:3000"
    depends_on:
      - backend-07
    restart: unless-stopped

volumes:
  postgres_data-07:
  qdrant_data-07:
  data-07:
